import React,{useEffect,useState}from"react";import{supabase}from"./supabase";
const money=n=>"৳"+Number(n||0).toLocaleString("bn-BD");
export default function Admin({session}){const[products,setProducts]=useState([]),[orders,setOrders]=useState([]),[tab,setTab]=useState("products"),[editing,setEditing]=useState(null),[form,setForm]=useState({name:"",price:"",stock:"",image_url:"",description:""}),[loading,setLoading]=useState(false);
async function load(){setLoading(true);const a=await supabase.from("products").select("*").order("created_at",{ascending:false});const b=await supabase.from("orders").select("*,order_items(*)").order("created_at",{ascending:false});setProducts(a.data||[]);setOrders(b.data||[]);setLoading(false)}useEffect(()=>{load()},[]);
function change(e){setForm({...form,[e.target.name]:e.target.value})}
function start(p){setEditing(p.id);setForm({name:p.name,price:p.price,stock:p.stock,image_url:p.image_url||"",description:p.description||""})}
async function save(e){e.preventDefault();const data={...form,price:Number(form.price),stock:Number(form.stock),updated_at:new Date().toISOString()};let r=editing?await supabase.from("products").update(data).eq("id",editing):await supabase.from("products").insert({...data,slug:form.name.toLowerCase().replace(/\\s+/g,"-")+"-"+Date.now()});if(r.error)alert(r.error.message);else{setEditing(null);setForm({name:"",price:"",stock:"",image_url:"",description:""});load()}}
async function del(id){if(!confirm("এই পণ্যটি মুছে ফেলবেন?"))return;const r=await supabase.from("products").delete().eq("id",id);if(r.error)alert(r.error.message);else load()}
async function status(id,status){const r=await supabase.from("orders").update({status}).eq("id",id);if(r.error)alert(r.error.message);else load()}
return <section className="admin"><div className="adminTop"><div><h1>Admin Panel</h1><p>{session?.user?.email||""}</p></div><button onClick={()=>supabase.auth.signOut()}>Logout</button></div><div className="tabs"><button onClick={()=>setTab("products")}>📦 Products</button><button onClick={()=>setTab("orders")}>🧾 Orders ({orders.length})</button></div>{tab==="products"?<><form className="adminForm" onSubmit={save}><h2>{editing?"পণ্য Edit করুন":"নতুন পণ্য যোগ করুন"}</h2><input name="name" value={form.name} onChange={change} placeholder="পণ্যের নাম" required/><input name="price" type="number" value={form.price} onChange={change} placeholder="দাম" required/><input name="stock" type="number" value={form.stock} onChange={change} placeholder="স্টক" required/><input name="image_url" value={form.image_url} onChange={change} placeholder="Image URL"/><textarea name="description" value={form.description} onChange={change} placeholder="বর্ণনা"/><button>{editing?"Update Product":"Add Product"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm({name:"",price:"",stock:"",image_url:"",description:""})}}>Cancel</button>}</form><div className="adminProducts">{products.map(p=><div className="adminProduct" key={p.id}><img src={p.image_url||"https://placehold.co/120"}/><div><b>{p.name}</b><p>{money(p.price)} · Stock {p.stock}</p></div><div><button onClick={()=>start(p)}>Edit</button><button className="danger" onClick={()=>del(p.id)}>Delete</button></div></div>)}</div></>:<div className="orders">{loading?<p>Loading...</p>:orders.map(o=><article className="order" key={o.id}><div><b>Order #{o.id.slice(0,8)}</b><p>👤 {o.customer_name} · 📞 {o.phone}</p><p>📍 {o.address}</p><p>💰 {money(o.total)}</p>{o.note&&<p>📝 {o.note}</p>}<small>{new Date(o.created_at).toLocaleString("bn-BD")}</small></div><div>{o.order_items?.map(i=><p key={i.id}>{i.product_name} × {i.quantity}</p>)}<select value={o.status} onChange={e=>status(o.id,e.target.value)}><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="processing">Processing</option><option value="shipped">Shipped</option><option value="delivered">Delivered</option><option value="cancelled">Cancelled</option></select></div></article>)}</div>}</section>}